version: '3.8'
services:
  backend:
   container_name: backend
   build: ./backend
   ports:
     - "5000:80"
   volumes:
     - logs:/app/logs
     - ./backend:/app
     - /app/node_modules
  frontend:
   container_name: frontend
   build: ./frontend
   ports:
     - "3000:3000"
   volumes:
     - ./frontend/src:/app/src
   stdin_open: true
   tty: true
   depends_on:
    - backend
volumes:
  data:
  logs: